apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: example-baremetalhost
  namespace: testmutatingwebhook
spec:
  online: true
  bmc:
    address: ipmi://192.168.122.1:6233
    credentialsName: example-baremetalhost-secret