apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mymutatingwebhook.example.com"
webhooks:
  - name: "mymutatingwebhook.example.com"
    namespaceSelector:
      matchLabels:
        webhook: enabled
    rules:
      - apiGroups:   ["metal3.io"]
        apiVersions: ["v1alpha1"]
        operations:  ["CREATE", "UPDATE"] # supported values: "*", "CONNECT", "CREATE", "DELETE", "UPDATE"
        resources:   ["baremetalhosts"]
    clientConfig:
      service:
        namespace: "mutatingwebhook"
        name: "mutatingwebhook"
        path: "/webhook"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ4ekNDQTYrZ0F3SUJBZ0lDQitNd0RRWUpLb1pJaHZjTkFRRUxCUUF3ZFRFTE1Ba0dBMVVFQmhNQ1ZWTXgKQ1RBSEJnTlZCQWdUQURFV01CUUdBMVVFQnhNTlUyRnVJRVp5WVc1amFYTmpiekViTUJrR0ExVUVDUk1TUjI5cwpaR1Z1SUVkaGRHVWdRbkpwWkdkbE1RNHdEQVlEVlFRUkV3VTVOREF4TmpFV01CUUdBMVVFQ2hNTlEyOXRjR0Z1CmVTd2dTVTVETGpBZUZ3MHlNVEF6TWpJeE1UQTFNekZhRncwek1UQXpNakl4TVRBMU16RmFNSFV4Q3pBSkJnTlYKQkFZVEFsVlRNUWt3QndZRFZRUUlFd0F4RmpBVUJnTlZCQWNURFZOaGJpQkdjbUZ1WTJselkyOHhHekFaQmdOVgpCQWtURWtkdmJHUmxiaUJIWVhSbElFSnlhV1JuWlRFT01Bd0dBMVVFRVJNRk9UUXdNVFl4RmpBVUJnTlZCQW9UCkRVTnZiWEJoYm5rc0lFbE9ReTR3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRREgKdEEva2JCK2tZOURvVFdsV29OTldCbXJsRWhMaGlHTmVqZWg3eTNJWjFGSmNkTW0rNnJxS0tmMTd3OEdjWnRLRApYdTlwVXNEcHM5dXg3T24ydGRKanlMRFB4SXVETnI2RnZCZXJMSDVwVFNSNEt2allVUnk4T0I5Ris1S1c5QU1ZCm8rOFZUdS84T3NmMEpCQ0F5MmFURHY4RGpPSitHcjlUTXMxTSswSmpPdWlmdlcyQmpvUzh5MHBJd3VLWUVkWEgKRFRoeFdzT0J1bWl2b2w4ZFRmNlBKaWNVWWFoS2JPRmw1dGpIU1BzdzlmcE5VYmtxM1R4cUJHV1pjWDRmVVNVcgpHQzBreC9RZWVvUUkwYmlhMXAvR3JoTWxtRytMTXQwTUFwUEkxbUFpRHZ2YTJXVzg2WnIvRHd5MnR6T09KV3QvCi9qNWtUa0FyZHIvOGE1ajZoQ3VPcWxtM3JhQWVKSVhHVSsxRGdWRHlDai9pdkV5M2FCRkRyWFBQWVJjbnM0UUYKZzY3LzhhYWJNZUdic3BwTm1jdU5mcUlHYWw5bmRCc3ZnZHhtNFhoZ28raDZxc1NUcWV3WnJyUXlxK01BeWx2aAprRnRucXdzby8yT2x6RHdDVGVLWE5FTW1pVUxjdjA5aW94b0NHa3J0RFEyaDY0N2RtN3BKc2hZWjFuMlNHSHZlCkRWVHQ3dVRjc0haN24yVXFRVGVnd0NJQU1DN0lXdW5Uc1BYS1JtR2hjblhvSHcvcDVlWTVkM3NQNGo0WDRURXQKU0RHMnVXOHdob1RRTkJCSS9yWDlteTVDM3FFcXUySm1MTjlSY2NpaTVuNW1JMmZjNGRkd3lsRUxqYnJ0V2p6QQowQ25SQmYzZXNFYU5xS2hoaWRmZklEVVpLSjFrYm5wWWI0emN0VGZMdHdJREFRQUJvMkV3WHpBT0JnTlZIUThCCkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRkJ3TUJNQThHQTFVZEV3RUIKL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkpkOVVlZlQ5N0oraC80bGxnQ3pmL0JEdkNTa01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUNBUUNiWm9KVHVHZTVNNTBick9sVHRVckh2QzFBY2ZnZnJZT3FGazJldzgrTmtYMDZ0VUxYCmxXUWp6OXNocXFpVTVxMldMbmZsZ0RWc3VsRmU3RC9nRkthNnlXbVlrOFphc3lwY3R4N3JJYTY4dVhxQjhmT1kKUXNpTWhDZmxpWUE2UlRQYk5VSk81d2xTWUFneXBDNGZZcVpJVzczYmVIR3VRZjdkUjh5bnVnQ3BpRGI5a2JCcApYK0lNK0tzODV2SFAxcFR6M3VNQlg3NGFsRlB6TWthd21WelFZdjhqZ3d1YzNtZDQ1QnFQT24zK2hNS0o0Zm5HCkFQSUZHd1ZMN1dzN2VaemNDcElVdXlCNDNRTHI0VlhmZXNhLzF6Ni8rSWFrWGVoSGY2TlNKYnA1enVsT3lEM3AKMW9oc2lzbGZlQ3NBclduanNuN3BMTlhQNGF2KzdiMkdCbk9UaE1FbzRMcnVoRzlzaEMxYUtwMitmMG1kRjRTVgprZWZIZmxlOHVUU0ppR0c5UWk0SzBnNG1HbDN1WjBtRXJtTEg5MkliSlFrNmMyY3lmMFdDcFpTcjlRSjhMckY0CjBJSW10LytjUlhVQUxEOVlrT25jTVdsdUlmL1E3NVBIS042djB6RVhUSjNQNnhzMmVySkdFTVdrMUlZZjZjLzIKQlF6NU1WR1NyL0JJWkpmR24vQVpCOTFqeGVFeDVyb08vcjErQngxNVVQZ01UUDJVQ1kvdmxpLzg3MDlMWnFuTgpXKzQ2WlNXMU1KWmhKR1ZWTWdUVDZsM3daM1Q5VGNQM0lmLzJOWHZabUxITXhDR2JRMk9SekV5YXd5emx2Zlo1ClVCSjA0Y2dBcWNpRWhmU1VpaWFwMnJkMWpaMndzWkx4Q21HTE1aQWhKNUZwbVl1RnJVRTUwZTd0bFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: v1
kind: Namespace
metadata:
  name: mutatingwebhook
---
apiVersion: v1
kind: Namespace
metadata:
  name: testmutatingwebhook
  labels:
    webhook: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutatingwebhook
  namespace: mutatingwebhook
  labels:
    app: mutatingwebhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutatingwebhook
  template:
    metadata:
      labels:
        app: mutatingwebhook
    spec:
      containers:
        - name: mutatingwebhook
          image: on2411/bmo-mutatingwebhook
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: mutatingwebhook
  namespace: mutatingwebhook
spec:
  selector:
    app: mutatingwebhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
